### ISSUE TITLE
No response after moving plugin window

### ISSUE THREAD

**Issue by inu20** [jsleroy/compare-plugin#70] opened 2017-03-28 02:44 UTC
I drag once time compare result window few days ago... and it make notepad++ no response for a while..

Since than, every time I move/stick other plugin window, my pc will frozen for 5 sec...

I have done full remove and reinstall it ( 7.3.3 and 7.3.2 ) many times, but still not back to normal.

Does anyone have same issue? Please help… > " <
English is not my first language, so please let me know if there have any mistake. > " <

**Comment by pnedev** [comment] 2017-04-06 07:54
Hello @inu20 ,

I have answered your query here: https://notepad-plus-plus.org/community/topic/13534/no-response-after-moving-plugin-window.

Any update on this?
Otherwise I'll close this issue, thanks.

BR

**Comment by pnedev** [comment] 2017-04-06 11:06
As the issue is not reproducible and as discussed at https://notepad-plus-plus.org/community/topic/13534/no-response-after-moving-plugin-window it doesn't seem CP problem I'm closing it.

**Closed as completed by pnedev** 2017-04-06 11:06 UTC
